version: '3.7'
services:
  user-service:
    image: aniljava/user-service:version1
    ports:
      - "5100:5100"
    restart: always
    depends_on: # Start the depends_on first
      - mysql 
    environment:
      RDS_HOST: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: users
    networks:
      - user-network

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: users
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    networks:
      - user-network 
  
# Volumes
volumes:
  mysql-database-data-volume:

networks:
  user-network: